//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanDoCongNghe.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tb_Contact
    {
        public int ContactID { get; set; }
        public Nullable<int> MaKH { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập họ và tên")]
        [StringLength(100, ErrorMessage = "Không nhập quá 100 ký tự")]
        public string HoTen { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập số điện thoại.")]
        [RegularExpression(@"^[0-9]{7,11}$", ErrorMessage = "Số điện thoại không hợp lệ.")]
        public string PhoneNumber { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập địa chỉ email.")]
        [EmailAddress(ErrorMessage = "Địa chỉ email không hợp lệ.")]
        public string Email { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập lý do.")]
        public string LyDo { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập nội dung.")]
        public string NoiDung { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> MaNhanVien { get; set; }
        public Nullable<bool> IsXuLy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }

        public virtual tb_NhanVien tb_NhanVien { get; set; }
        public virtual tb_Customer tb_Customer { get; set; }
    }
}
