//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanDoCongNghe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_Product()
        {
            this.tb_ChiTietOrder = new HashSet<tb_ChiTietOrder>();
            this.tb_ChiTietOrder_Traveler = new HashSet<tb_ChiTietOrder_Traveler>();
            this.tb_ProductImages = new HashSet<tb_ProductImages>();
            this.tb_FavoriteProduct = new HashSet<tb_FavoriteProduct>();
            this.tb_ProductReview = new HashSet<tb_ProductReview>();
        }
    
        public int MaSanPham { get; set; }
        public string TenSanPham { get; set; }
        public string Description { get; set; }
        public string Detail { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> PriceSale { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string ImageProduct { get; set; }
        public string Link { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsSoldOut { get; set; }
        public Nullable<bool> IsSale { get; set; }
        public Nullable<bool> IsNew { get; set; }
        public Nullable<bool> IsHot { get; set; }
        public string SeoTitle { get; set; }
        public string SeoDescription { get; set; }
        public string SeoKeywords { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<int> MaProductCategory { get; set; }
        public Nullable<int> MaBrand { get; set; }
        public Nullable<int> MaColor { get; set; }
        public Nullable<int> MaMemory { get; set; }
    
        public virtual tb_Brand tb_Brand { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_ChiTietOrder> tb_ChiTietOrder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_ChiTietOrder_Traveler> tb_ChiTietOrder_Traveler { get; set; }
        public virtual tb_Color tb_Color { get; set; }
        public virtual tb_Memory tb_Memory { get; set; }
        public virtual tb_ProductCategory tb_ProductCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_ProductImages> tb_ProductImages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_FavoriteProduct> tb_FavoriteProduct { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_ProductReview> tb_ProductReview { get; set; }
    }
}
