//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanDoCongNghe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_PhanQuyen
    {
        public int MaChucNang { get; set; }
        public int MaNhanVien { get; set; }
        public string Description { get; set; }
    
        public virtual tb_ChucNang tb_ChucNang { get; set; }
        public virtual tb_NhanVien tb_NhanVien { get; set; }
    }
}
