//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanDoCongNghe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Traveler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_Traveler()
        {
            this.tb_ChiTietOrder_Traveler = new HashSet<tb_ChiTietOrder_Traveler>();
        }
    
        public int MaDonHang { get; set; }
        public string HoTen { get; set; }
        public string Email { get; set; }
        public string PhoneNumber1 { get; set; }
        public string PhoneNumber2 { get; set; }
        public string Address { get; set; }
        public string Ghichu { get; set; }
        public Nullable<decimal> TotalPayment { get; set; }
        public Nullable<int> MaPhuongThucThanhToan { get; set; }
        public Nullable<bool> IsThanhToan { get; set; }
        public Nullable<bool> IsHoanThanh { get; set; }
        public Nullable<bool> IsHuyDon { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> IsXacNhan { get; set; }
        public string TrangThaiDon { get; set; }
        public Nullable<int> MaNhanVien { get; set; }
        public Nullable<bool> IsDongGoi { get; set; }
        public Nullable<bool> IsVanChuyen { get; set; }
        public string LyDoHuyDon { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_ChiTietOrder_Traveler> tb_ChiTietOrder_Traveler { get; set; }
        public virtual tb_PhuongThucThanhToan tb_PhuongThucThanhToan { get; set; }
        public virtual tb_NhanVien tb_NhanVien { get; set; }
    }
}
